### ISSUE TITLE
[BUG BOUNTY] No default case of paymentMethod

### ISSUE THREAD

**Issue by hamza-siddiq** [masa-finance/bug-bounty#10]
**Describe the bug**
No default case found for switch of paymentMethod

**To Reproduce**
1. Go to [switch (paymentMethod)](https://github.com/masa-finance/masa-sdk/blob/fb6ff5cc8fcdb802f43657a7114a53b74b7f3b60/src/contracts/masa-contracts.ts#L24) at masa-sdk/src/contracts/masa-contracts.ts
2. See error

**Expected behavior**
Default case present in switch (paymentMethod)

**Desktop (please complete the following information):**
 - N/A

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
It might be a good idea to have the default case output an error, incase anything goes wrong.

**Is this bug a Critical Vulnerability**
N

**Comment by H34D** [comment]
the default case is this one: https://github.com/masa-finance/masa-sdk/blob/fb6ff5cc8fcdb802f43657a7114a53b74b7f3b60/src/contracts/masa-contracts.ts#L22
