### ISSUE TITLE
[BUG BOUNTY] Null comparison without type-checking operator

### ISSUE THREAD

**Issue by hamza-siddiq** [masa-finance/bug-bounty#11]
**Describe the bug**
Comparing to null without a type-checking operator (=== or !==), can have unintended results as the comparison will evaluate to true when comparing to not just a null, but also an undefined value.

**To Reproduce**
1. Go to [masa-contracts-identity/src/minter-addresses-goerli.ts](https://github.com/masa-finance/masa-contracts-identity/blob/main/src/minter-addresses-goerli.ts) and [masa-contracts-identity/src/minter-addresses-alfajores.ts](https://github.com/masa-finance/masa-contracts-identity/blob/main/src/minter-addresses-alfajores.ts)
3. Scroll down to [Line 163](https://github.com/masa-finance/masa-contracts-identity/blob/a7ba04d373fcff5ec182d3d03f9e71ae14bbfc81/src/minter-addresses-goerli.ts#L163) and [Line 172](https://github.com/masa-finance/masa-contracts-identity/blob/a7ba04d373fcff5ec182d3d03f9e71ae14bbfc81/src/minter-addresses-goerli.ts#L172) at minter-addresses-goerli.ts. and [Line 94](https://github.com/masa-finance/masa-contracts-identity/blob/a7ba04d373fcff5ec182d3d03f9e71ae14bbfc81/src/minter-addresses-alfajores.ts#L94) at minter-addresses-alfajores.ts.
4. See error. 

**Expected behavior**
Use === to compare with null.

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Is this bug a Critical Vulnerability**
N

**Comment by H34D** [comment]
this is non productive code, no need
