### ISSUE TITLE
Bug - Cannot access prosperity website to mint .celo domain

### ISSUE THREAD

**Issue by Sventar** [masa-finance/bug-bounty#12]
When clicking in the link to access Prosperity Passport App: https://app.prosperity.global/.  The screen goes white before you can click an option.  I switched to the Celo chain in my Metamask wallet before accessing the site.
**To Reproduce**
1. Go to Masa Discord - Announcements (I couldn't wait!)
2. Clicked on link - Click on link(https://app.prosperity.global/.  ( I was so excited!)
3. WHITE SCREEN OF DEATH

**Expected behavior**
I expected to have access to the prosperity website to mint a .celo domain and maybe check out those sweet rewards...

**Screenshots**
No need.  You guys got this!

**Desktop (please complete the following information):**
 - OS: [iOS - 11.4]
 - Browser [Chrome]
 - Version [110]

**Additional context**

**Is this bug a Critical Vulnerability**
no - but it sure doesn't help anything

**Comment by H34D** [comment]
Hello, thanks for reporting. 

You chrome version: 
> * Version [22]

is very old. The current version is 111. Please update chrome and retry.

**Comment by Sventar** [comment]
I apologize.  I did not update my version when using the form template.  I am running Chrome. v110

**Comment by H34D** [comment]
> I apologize. I did not update my version when using the form template. I am running Chrome. v110

Please fill out the correct values here:

OS: [xx]
Browser [xx]
Version [xx]

**Comment by Sventar** [comment]
OS: [iOS 11.4]
Browser [Chrome]
Version [110]

**Comment by Sventar** [comment]
I updated my desktop info in the report.  Again, sorry for the error and any delay it caused.

**Comment by Sventar** [comment]
Thanks guys.  Tested today and it worked.  I could access the site and minted a .celo domain successfully.  The GUI on the site seems a little off.  The (rewards and domain mint) buttons were blank but functional.  May be an issue on my end with my desktop but the important parts are working!  If it's a Friday where you are located take the afternoon off!  You've earned it!!
