### ISSUE TITLE
[BUG BOUNTY] : Security vulnerability in masa.finance

### ISSUE THREAD

**Issue by ajay1706** [masa-finance/bug-bounty#14]
**Describe the bug**
I have found a subdomain takeover bug in masa.finance subdomain. It is pointing to vercel which can be used by attacker to takeover its subdomain. It means one of your pages are built on vercel and now there is nothing in it but still uses your subdomain which can be taken over by any attacker on your name and misuse it.

One should never keep this websites empty which are built on third party sites if they are not in use as that can be easily takeover by dangling DNS records and CNAME. 

Reference to similar subdomain takeover - 
https://hackerone.com/reports/197489

Similar vulnerabilities reported by me in the past has been fixed and rewarded this way:

primitive.finance
[alpha.daylight.xyz](http://alpha.daylight.xyz/)
https://partner.sushi.com

** Vulnerable url :**
Go to https://test.masa.finance

You will see there is nothing on the subdomain and is empty and open to takeover and attacker just need to assign a project there. 
For this we need a CNAME of the subdomain which is [cname.vercel-dns.com](http://cname.vercel-dns.com/)

<img width="1436" alt="Screenshot 2023-07-03 at 7 57 23 PM" src="https://github.com/masa-finance/bug-bounty/assets/20722807/5d49055f-7b4d-4e24-9e01-cad7cc7f1413">

I was able to confirm the vercel subdomain takeover using the fingerprint and the CNAME but didn't takeover due to the sole reason it needs to take premium account 

**Another subdomain vulnerable to similar vulnerability:**
https://beta.masa.finance

**Impact:**
Attacker can takeover the subdomain and can misuse by creating fake masa.finance  page  and much more which will harm the company's name and can trick users to go to his page. 

fake website
malicious code injection
users tricking
company impersonation
This issue can have really huge impact on the companies reputation someone could post malicious content on the compromised site and then your users will think it's official but it's not.

**Remediation:**
Remove  the website if its not in use

**Is this bug a Critical Vulnerability**
Y

**Comment by H34D** [comment]
i just beta.masa.finance and test.masa.finance thanks for reporting!

**Comment by ajay1706** [comment]
> I just deleted beta.masa.finance and test.masa.finance. Thanks for reporting!

Hey Your welcome. May I know an update on the bounties for the same for reporting multiple security vulnerabilities responsibly ? Hope to get an update soon. Thanks

**Comment by ajay1706** [comment]
@H34D  Adding the reference of the similar third party subdomain takeover I have found in magiceden too also you can check immunefi which is a web3 bug bounty program for companies you can check where subdomain takeover is considered as a critical security vulnerability in webapps too. 
Hope to get an update on bounties soon. Thanks
![photo_2023-05-09 00 16 29](https://github.com/masa-finance/bug-bounty/assets/20722807/5b145e5f-5c66-4ed9-80e6-c1b2bec20fa6)

**Comment by ajay1706** [comment]
Hey @H34D May I know update on the bounties for responsibly reporting multiple security vulnerabilities?

**Comment by H34D** [comment]
you can find all the details here: https://github.com/masa-finance/bug-bounty#mega-instructions

**Comment by ajay1706** [comment]
Hey @H34D Yes I have seen that, but tis were the valid critical vulnerabilities according to the immunefi web3 bug bounty program and others too, even if they don’t deserve as much as your smart contracts but still this vulnerabilities deserve a bounty for reporting them responsibly. Hope you understand and asses the bounty and given an update ASAP thanks

**Comment by H34D** [comment]
The Bug Bounty Program is limited to the repos listed here: https://github.com/masa-finance/bug-bounty#computer-repositories-for-bug-bounty

[Masa Bug Bounty](https://github.com/masa-finance/bug-bounty)
[Masa Smart Contracts](https://github.com/masa-finance/masa-contracts-identity)
[Masa CLI](https://github.com/masa-finance/masa-cli)
[Masa SDK](https://github.com/masa-finance/masa-sdk)
[Masa React](https://github.com/masa-finance/masa-react)
[Masa Docs](https://github.com/masa-finance/docs)
[Masa Protocol](https://github.com/masa-finance/masa-protocol)

**Comment by ajay1706** [comment]
@H34D I have checked the scope before submitting vulnerabilities but on discord  a person from you team has asked to report it either way, Even after checking the report I was asked to report it  and make a complete report and then if i won’t get rewarded and it gets fixed then whats the point of reporting it then ? Hope you understand, one should directly said not to report if its in website, we find a vulnerability and then make a complete report and later if not get rewarded that doesn’t sound good after putting efforts

**Comment by ajay1706** [comment]
Stop taking someones work for free, just be on your words from the beginning, if you don’t reward for website bugs just say it clearly at the start but don’t act smart, its not how being a professional works
