### ISSUE TITLE
[BUG BOUNTY]

### ISSUE THREAD

**Issue by shuaibwasifkhan** [masa-finance/bug-bounty#15]
**Describe the bug**
when trying to register new .soul name getting error
cannot estimate gas; transaction may fail or may require manual gas limit

**To Reproduce**
1. Go to [app.masa.finance](https://app.masa.finance/)
2. Click on 'mint'
3. after some time waiting getting error
cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x2Ebcd5d751C5ea788EbcA0032F5Bd23dAa0564c7","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x064dcf9e98"},"to":"0x1C7652919598b32C576D362E74F44C6E34EF7Aba","value":{"type":"BigNumber","hex":"0x12e53119a580fc"},"data":"0xf615283a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000001200000000000000000000000005b45daa4645f79a419811dc0657fa1b2695c6ab7000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000000067377656574790000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003061723a2f2f554e6550364a64736d6576574935556a4d5861385767536869432d5463707a504d5134664b4f4b77593677000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041f40999fcfce13f2274224e41e7df40ed05ea2f5c2e2b85dea3dcd419a77db9887cda04e45a55f300541e997d1bba6a1151f6613d9335a70c19c1d572f611e1851c00000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32000,"message":"execution reverted"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)

**Expected behavior**
mint my domain

**Screenshots**
<img width="960" alt="image" src="https://github.com/masa-finance/bug-bounty/assets/42069283/74b021e5-1c8d-4b23-823b-e3c1cad869cc">

**Video**
If applicable, add a video to help explain your problem. 

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser chrome
 - Version newest updated yesterday

**Is this bug a Critical Vulnerability**
Yes

**Comment by shuaibwasifkhan** [comment]
having 100 usd eth in wallet so its not fee problem

**Comment by H34D** [comment]
thats a network related issue, please try again when the network is not fully utilised
