### ISSUE TITLE
[BUG BOUNTY] Private Reporting Channel

### ISSUE THREAD

**Issue by umbr4g3** [masa-finance/bug-bounty#17]
I've discovered a vulnerability that would allow an attacker to gain and foothold and potentially take over Masa cloud infrastructure in AWS. Since this is a public issue list I don't think it's appropriate to report here.

Do you have an email address I can send a report to?

**Comment by H34D** [comment]
> Do you have an email address I can send a report to?

@umbr4g3 thanks for reaching out. Please send your report to: koteve2186@bayxs.com

**Comment by H34D** [comment]
> Thanks! Will send soon

it seems there was a problem with the email provider, can you please send the report to help@masa.finance?

**Comment by teslashibe** [comment]
@umbr4g3, we have not received the email from you to that email address.

**Comment by H34D** [comment]
> Please let me know via email or here once you've been able to access the report so I can remove the shared file link (as the contents of the report are quite sensitive)
> 
> @teslashibe @H34D

we received the report and put countermeasures in place. thank you!

**Comment by teslashibe** [comment]
@umbr4g3 we will follow up regarding bounty by email - we are closing the issue for now. Thanks so much
