### ISSUE TITLE
Impossible to create a soul Name even though it is available on Metamask with letter and emoji[BUG BOUNTY]

### ISSUE THREAD

**Issue by Jojohnt29** [masa-finance/bug-bounty#7]
**Describe the bug**
When we go to Metamask, on the browser we go to the masa-finance site and we try to acquire the soul name, the page loads and we get nothing. 

**To Reproduce**
1. Go to 'Metamask, then browser, type Masa Finance URL '
2. Click on 'Connect wallet then create your soul in such a way that it puts available, this time puts a letter and an emoji so that it makes available '
3. Scroll down to 'Then select the number of years and all that follows, launch my creation of the name soul'

**Expected behavior**
I hope that in the future, we can create soul names with emoji and combined letters. 

**Screenshots**

**Video**
If applicable, add a video to help explain your problem. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Huawei 9s
 - OS: EMUI 12
 - Browser METAMASK BROSWER
 - Version :2

**Additional context**

**Is this bug a Critical Vulnerability**
N

**Comment by H34D** [comment]
what was the exact soul name? i just tested this flow on the metamask mobile browser and it worked well

**Comment by Jojohnt29** [comment]
The exact name of this soul Name is "🤣.soul"Envoyé depuis mon téléphone-------- Message original --------De : Sebastian Gerske ***@***.***>Date : lun. 19 déc. 2022 à 10:28À : masa-finance/bug-bounty ***@***.***>Cc : Jojohnt29 ***@***.***>, Author ***@***.***>Objet : Re: [masa-finance/bug-bounty] Impossible to create a soul Name even though it is available on Metamask with letter and emoji[BUG BOUNTY] (Issue #7)
what was the exact soul name? i just tested this flow on the metamask mobile browser and it worked well

**Comment by H34D** [comment]
I can confirm that, we are not supporting this emoji right now:

`ERROR STORAGE ERROR Error: ENOENT: no such file or directory, open 'face_with_rolling_eyes.png'`

@Luka-Loncar

**Comment by Jojohnt29** [comment]
Thank you for the clarification.

Le lun. 19 déc. 2022 à 15:40, Sebastian Gerske ***@***.***> a
écrit :
