### ISSUE TITLE
[BUG BOUNTY] Smart Contracts Function: purchaseName

### ISSUE THREAD

**Issue by juhyarmaulana** [masa-finance/bug-bounty#9]
**Describe the bug**
User/attacker can modify _tokenURI (string) with custom value

**To Reproduce**
1. Go to contract -> write contract.
2. Click on connect to web3 and connect with metamask
3. Scroll down to 5. purchaseName
4. Fill in the blanks according to the description, payableAmount can calculate at masa page https://beta.claimyoursoul.masa.finance/app/hub/register-soulname
5. _tokenURI (string) (potential bug), i tried to make a json file, like the one used by masa and change some values like image and others, and upload it to arweave 

**Expected behavior**
As I thought, the transaction was successful and I have a soul with a different image, or a different description!?
https://testnets.opensea.io/assets/goerli/0xb4ca4a32199520f726edd680042a8d9d26b4de06/4088

**Screenshots**
![masatokenurl](https://user-images.githubusercontent.com/50315297/208829235-44e86abc-169a-49ee-8e9a-125cda630edb.png)
![masawrite](https://user-images.githubusercontent.com/50315297/208829280-1fa80554-d4c5-422f-9b58-fbdb233a719c.png)
![masajsondata](https://user-images.githubusercontent.com/50315297/208829337-054d505b-b7c6-4dfc-be16-6a3f9c9feb2b.png)
![masaapesea](https://user-images.githubusercontent.com/50315297/208829468-1df14994-c7a0-4320-a02f-1d235a617200.png)

**Desktop (please complete the following information):**
 - OS: EndeavourOS
 - Browser: Chromium
 - Version: 108.0.5359.124 (Official Build) Arch Linux (64-bit)

**Additional context**
This looks like it's dangerous, it can manipulate image captions and others for the worse, input from me don't allow the user to change the _tokenURI (string) or add additional signature so that the user can't change it, it means what it should

**Is this bug a Critical Vulnerability**
Y

I am sorry, my English is not good

**Comment by H34D** [comment]
Thanks for flagging this!

It seems something is not correct with the arweave transaction i can lead it in the arweave app and i can get the data from arweave.net when i request it. But when i load it form the API it gives me 404:

https://arweave.net:443/tx/DejQsSK2GlxgFO4BXyG12FhUEKX_u9LzBphKN6IVkks/status -> 
{ status: 404, confirmed: null }

https://arweave.app/tx/DejQsSK2GlxgFO4BXyG12FhUEKX_u9LzBphKN6IVkks works
https://arweave.net/DejQsSK2GlxgFO4BXyG12FhUEKX_u9LzBphKN6IVkks works as well

also using other nodes it does not show up: http://178.62.222.154:1984/tx/DejQsSK2GlxgFO4BXyG12FhUEKX_u9LzBphKN6IVkks/status
-> not found

It seems that this problem occurs sometimes when a bundle is used in arweave

Regarding the issue itself: this is a common problem for NFT projects. We are working with a Merkel like verification of the metadata and can rule out metadata that has not been generated by us.

**Comment by H34D** [comment]
Based on your contribution i hardened the SDK code a little bit to support correct verification with the masa-cli:

```bash
$ npx @masa-finance/masa-cli@latest soul-name verify thisisbugmasa.soul
  __  __                            ____   _       ___
 |  \/  |   __ _   ___    __ _     / ___| | |     |_ _|
 | |\/| |  / _` | / __|  / _` |   | |     | |      | |
 | |  | | | (_| | \__ \ | (_| |   | |___  | |___   | |
 |_|  |_|  \__,_| |___/  \__,_|    \____| |_____| |___|

Failed to load arweave tx id: DejQsSK2GlxgFO4BXyG12FhUEKX_u9LzBphKN6IVkks getting https://arweave.net:443/DejQsSK2GlxgFO4BXyG12FhUEKX_u9LzBphKN6IVkks instead
Failed to load metadata transaction! DejQsSK2GlxgFO4BXyG12FhUEKX_u9LzBphKN6IVkks
Failed to load image transaction! gm4e62gtk5ZUQZP2VAQxMqxKgSlEUpywyuYRpEzQOIU
Failed to load arweave tx id: gm4e62gtk5ZUQZP2VAQxMqxKgSlEUpywyuYRpEzQOIU getting https://arweave.net:443/gm4e62gtk5ZUQZP2VAQxMqxKgSlEUpywyuYRpEzQOIU instead
{
  result: {
    nameMatch: true,
    imageOwnerIsMasaAccount: false,
    imageHashMatch: false,
    imageSignatureMatch: false,
    metadataSignatureMatch: false,
    metadataOwnerIsMasaAccount: false
  }
}
```

**Comment by H34D** [comment]
a valid soul name would return:

```bash
npx @masa-finance/masa-cli@latest soul-name verify test.soul
  __  __                            ____   _       ___
 |  \/  |   __ _   ___    __ _     / ___| | |     |_ _|
 | |\/| |  / _` | / __|  / _` |   | |     | |      | |
 | |  | | | (_| | \__ \ | (_| |   | |___  | |___   | |
 |_|  |_|  \__,_| |___/  \__,_|    \____| |_____| |___|

{
  result: {
    nameMatch: true,
    imageOwnerIsMasaAccount: true,
    imageHashMatch: true,
    imageSignatureMatch: true,
    metadataSignatureMatch: true,
    metadataOwnerIsMasaAccount: true
  }
}
```

**Comment by H34D** [comment]
i added a follow up on the arweave discord: https://discord.com/channels/357957786904166400/358038065974870018/1055123719711895612

**Comment by H34D** [comment]
@juhyarmaulana with the latest version of the smart contracts we added a signature to the minting process of the soul names. Thank you for your contribution! Really appreciated.

**Comment by juhyarmaulana** [comment]
Nice, glad to have contributed.

**Comment by teslashibe** [comment]
@juhyarmaulana please send us an email at help@masa.finance so we can arrange bounty

**Comment by juhyarmaulana** [comment]
Email sent from juhyar.maulana@gmail.com
Thanks.
